spring.application.name=devsync

spring.datasource.url=jdbc:postgresql://localhost:5432/devsync
spring.datasource.username=postgres
spring.datasource.password=Natasha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true